spring.application.name=NoteApp2
spring.data.mongodb.uri=mongodb+srv://vanshtomar1303:MoTgsCkT6sjnBesi@cluster0.ydsidif.mongodb.net/notes?retryWrites=true&w=majority&appName=Cluster0
jwt.secret=ZG4zOTRiZjM4MjluZHd9238dhhd293420fhsk4h8rh9d3no
spring.data.mongodb.auto-index-creation=true