spring.application.name=SimpleBlogApi
jwt.secret=ZG4zOTRiZjM4MjLuZHd9238dhHd293420fhSk4h8rh9d3no
spring.data.mongodb.uri=mongodb+srv://vanshtomar1303:lZ5gtR7u2LgKvwuQ@blogapi3.x5ykbfe.mongodb.net/blogapi?retryWrites=true&w=majority&appName=BlogApi3
spring.data.mongodb.auto-index-creation=true